### ISSUE TITLE
{#Notif} add notif for service

### ISSUE THREAD

**Issue by Lozyboobob** [weareopensource/storytelling#374]
add notification for service response status:

- [x] add slides
- [x] delete slides
- [x] copy slides
- [x] set favorite/unfavorte
- [x] set upload/not upload

- [x] upload pic

**Comment by cherifa-ghersi** [comment]
I think we can use angular matrial snack-bar ?

**Comment by Lozyboobob** [comment]
@cherifa-ghersi yes, i am using this ^ ^
