### ISSUE TITLE
Code Refactor Slides Editor

### ISSUE THREAD

**Issue by farhatmo** [weareopensource/storytelling#386]
![screen shot 2017-07-10 at 16 21 04](https://user-images.githubusercontent.com/6069599/28022903-b81fe134-658c-11e7-98a8-f3f77f305fd9.png)

**Comment by PierreBrisorgueil** [comment]
to discuss


sorytellings
- models
- services
- components 
- - list
- - - list-sorytellings.component.html
- - - list-sorytellings.component.ts
- - - list-sorytellings.component.scss
- - view
- - - view-sorytelling.component.html
- - - view-sorytelling.component.ts
- - - view-sorytelling.component.scss
- - form
- - - form-sorytelling.component.html
- - - form-sorytelling.component.ts
- - - form-sorytelling.component.scss
- - slides
- - - - list 
- - - - - list-slides.component.html
- - - - - list-slides.component.ts
- - - - - list-slides.component.scss
- - - - view 
- - - - - view-slide.component.html
- - - - - view-slide.component.ts
- - - - - view-slide.component.scss
- - - - form 
- - - - - form-slide.component.html
- - - - - form-slide.component.ts
- - - - - form-slide.component.scss
- - - - graph
- - - - - builder-graph.component.html
- - - - - builder-graph.component.ts
- - - - - builder-graph.component.scss
