### ISSUE TITLE
{#Chart} some ngchart doesn't work

### ISSUE THREAD

**Issue by Lozyboobob** [weareopensource/storytelling#433]
Bar Vertical 2D
Bar Horizontal 2D
Bar Vertical Stacked
Bar Vertical Normalized

**Comment by cherifa-ghersi** [comment]
@Lozyboobob for me the 4 graph work can you give more details ?
![capture du 2017-08-30 15-35-54](https://user-images.githubusercontent.com/9610810/29875105-2a3d56d2-8d99-11e7-9489-b99462610c8c.png)
![capture du 2017-08-30 15-35-21](https://user-images.githubusercontent.com/9610810/29875106-2a3e931c-8d99-11e7-9e21-cbc51c9eadd9.png)
![capture du 2017-08-30 15-34-07](https://user-images.githubusercontent.com/9610810/29875107-2a3fb508-8d99-11e7-9f43-268a4fac29eb.png)
![capture du 2017-08-30 14-57-46](https://user-images.githubusercontent.com/9610810/29875108-2a44596e-8d99-11e7-9106-4df585af5865.png)
