### ISSUE TITLE
bound csv input to every chart

### ISSUE THREAD

**Issue by Lozyboobob** [weareopensource/storytelling#5]

**Comment by PierreBrisorgueil** [comment]
to discuss with @AmbroiseKritz in order to use same system like soos and map data to graph dimension

**Comment by Lozyboobob** [comment]
Soos use a javascript module, but for now i didn't use module for this part. Do i have to change?

**Comment by PierreBrisorgueil** [comment]
what do you mean by to change ? add dependencies ? 

it's for r2 of the project, not require for the r1 :)

**Comment by Lozyboobob** [comment]
Yes, add dependencies.

**Comment by PierreBrisorgueil** [comment]
yes no problem to add dependencies for course :) but we will see css for the R2 :)

**Comment by Lozyboobob** [comment]
Now it's transfer in browser
